# Generated by Django 4.0.6 on 2022-07-19 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_website_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='website',
            name='thumbnail',
            field=models.ImageField(default='Nana.jpg', upload_to='website_thumbnail/'),
            preserve_default=False,
        ),
    ]
