# Generated by Django 4.0.6 on 2022-07-19 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_category_options_category_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='desc',
        ),
    ]
