# Generated by Django 4.0.6 on 2022-07-20 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_image_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('siteName', models.CharField(max_length=100)),
                ('siteDesc', models.TextField()),
                ('siteCategory', models.CharField(choices=[('website', 'Website'), ('graphic', 'Graphic'), ('photography', 'Photography')], max_length=100)),
                ('thumbnail', models.ImageField(upload_to='website_thumbnail/')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.AlterField(
            model_name='image',
            name='website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.site'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
