# Generated by Django 4.0.6 on 2022-07-20 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_site_alter_image_website_delete_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='website',
            new_name='site',
        ),
    ]
