# Generated by Django 4.0.6 on 2022-07-20 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_rename_website_image_site'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image_website/'),
        ),
        migrations.AlterField(
            model_name='site',
            name='siteName',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
