# Generated by Django 4.0.6 on 2022-07-20 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_image_image_alter_site_sitename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.site'),
        ),
    ]
