# Generated by Django 4.0.6 on 2022-07-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_image_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='externalLink',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='github',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
