# Generated by Django 4.0.6 on 2022-07-25 08:42

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_site_externallink_site_github'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='createDate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='site',
            name='updateDate',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
