# Generated by Django 4.0.6 on 2022-07-26 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_rename_site_work_alter_work_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='youtube',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
